# Application Programming Interface:

In [1]:
import requests

In [15]:
URL = "http://api.citybik.es/v2/networks"

In [23]:
res = requests.get(URL)

In [28]:
json_data = res.json()

In [31]:
import pandas as pd

df = pd.json_normalize(json_data["networks"])
df = df[["id" , "name" , "href" , "company"]]
df

,id,name,href,company
0,abu-dhabi-careem-bike,Abu Dhabi Careem BIKE,/v2/networks/abu-dhabi-careem-bike,[Careem]
1,acces-velo-saguenay,Accès Vélo,/v2/networks/acces-velo-saguenay,[PBSC Urban Solutions]
2,aksu,Aksu,/v2/networks/aksu,[阿克苏公共服务]
3,alba,Alba,/v2/networks/alba,[Comunicare S.r.l.]
4,albabici,AlbaBici,/v2/networks/albabici,[Instituto Tecnológico de Castilla y León (ITCL)]
...,...,...,...,...
795,youbike-taoyuan,YouBike,/v2/networks/youbike-taoyuan,"[YouBike Co., Ltd.]"
796,yverdon-les-bains,Donkey Republic Yverdon-les-Bains,/v2/networks/yverdon-les-bains,[Donkey Republic]
797,zarskie-rowery,Żarskie Rowery,/v2/networks/zarskie-rowery,[ROOVEE S.A.]
798,zebullo,ZébullO,/v2/networks/zebullo,[Ecovelo]
799,zena-by-bike,Zena By Bike,/v2/networks/zena-by-bike,[Bicincitta Italia S.r.l.]

## NEW API call (Scrapethissite)

In [3]:
URL = "https://www.scrapethissite.com/pages/simple/"
res = requests.get(URL)

In [5]:
res.status_code

200

In [10]:
if res.status_code == 200:
    print(res.headers)

with open("scrapped_data/data1.html" , "w" , encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Tue, 21 Jul 2026 12:15:44 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=6Vrr6ZZnlYPoG3USxFgPtzid%2Bho1pxS2zvgD%2FM2XfQc%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1784636143"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=6Vrr6ZZnlYPoG3USxFgPtzid%2Bho1pxS2zvgD%2FM2XfQc%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1784636143"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': 'a1ea21f78a0bff23-KHI', 'alt-svc': 'h3=":443"; ma=86400'}

## For try and catch:

In [12]:
try:  
    r = requests.get("https://www.scrapethissite.com//simple/" , timeout=5)  
    r.raise_for_status()   
# Raises error for 4xx/5xx responses  
except requests.exceptions.RequestException as e:  
    print("Error:", e)

Error: 404 Client Error: Not Found for url: https://www.scrapethissite.com//simple/

## HEaders:

In [ ]:
headers = {  
    "User-Agent": "Mozilla/5.0"  
}  
response = requests.get("https://www.scrapethissite.com/simple/", headers=headers) 
print(response.text)

# BeautifulSoup...

In [15]:
from bs4 import BeautifulSoup

In [18]:
with open("scrapped_data/data1.html" , "r" , encoding="utf-8") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content , "lxml")

In [46]:
all_h3 = soup.find_all("h3")


country_info = [ ]

for h3 in all_h3:
    country_names = h3.get_text(strip = True)   
    country_capitals = h3.find_next("div").select("span.country-capital")[0].get_text(strip = True)
    country_info.append([country_names , country_capitals])

In [53]:
import pandas as pd
df = pd.DataFrame(country_info , columns= ["Country Name" , "Country Capital"])
df

             Country Name   Country Capital
0                 Andorra  Andorra la Vella
1    United Arab Emirates         Abu Dhabi
2             Afghanistan             Kabul
3     Antigua and Barbuda        St. John's
4                Anguilla        The Valley
..                    ...               ...
245                 Yemen             Sanaa
246               Mayotte         Mamoudzou
247          South Africa          Pretoria
248                Zambia            Lusaka
249              Zimbabwe            Harare

[250 rows x 2 columns]

In [55]:
df.to_csv("AR_cleaning/cleaned_data1.csv" , index=False)